image: Visual Studio 2017
artifacts:
  - path: '**\jsreport.MVC*.nupkg'
    name: nuget
    type: NuGetPackage
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
  project: jsreport.MVC.sln
before_build:
  - cmd: dotnet restore
deploy:
  provider: NuGet
  api_key:
    secure: 8YEU/HfxJmYnx+WcWGi7Lay3uoTDIfDh3R2CdEhDsUZpoDmqK9g4IP1xq+NnwDLM
  on:
    appveyor_repo_tag: true